<template>
  <div class="province" v-p-echarts="provinceOption">

  </div>
</template>

<script>
require('echarts/map/js/province/anhui')
require('echarts/map/js/province/shandong')
require('echarts/map/js/province/guangdong')
require('echarts/map/js/province/aomen')
require('echarts/map/js/province/beijing')
require('echarts/map/js/province/chongqing')
require('echarts/map/js/province/fujian')
require('echarts/map/js/province/guangxi')
require('echarts/map/js/province/guizhou')
require('echarts/map/js/province/hainan')
require('echarts/map/js/province/hebei')
require('echarts/map/js/province/heilongjiang')
require('echarts/map/js/province/henan')
require('echarts/map/js/province/hubei')
require('echarts/map/js/province/hunan')
require('echarts/map/js/province/jiangsu')
require('echarts/map/js/province/jiangxi')
require('echarts/map/js/province/jilin')
require('echarts/map/js/province/liaoning')
require('echarts/map/js/province/neimenggu')
require('echarts/map/js/province/ningxia')
require('echarts/map/js/province/qinghai')
require('echarts/map/js/province/shanghai')
require('echarts/map/js/province/shanxi')
require('echarts/map/js/province/sichuan')
require('echarts/map/js/province/tianjin')
require('echarts/map/js/province/xianggang')
require('echarts/map/js/province/xinjiang')
require('echarts/map/js/province/xizang')
require('echarts/map/js/province/yunnan')
require('echarts/map/js/province/zhejiang')

export default {

  name: 'province',

  data () {
    return  {
      provinceOption: {},
      province: this.$route.params.area
    }
  },

  created () {
    this.provinceOption = {
      tooltip : {
          trigger: 'item'
      },
      toolbox: {
          show : true,
          orient: 'vertical',
          x:'right',
          y:'center',
          feature : {
              mark : {show: true},
              dataView : {show: true, readOnly: false}
          }
      },
      series: [
        {
          tooltip: {
              trigger: 'item',
              formatter: '{b}'
          },
          name: '选择器',
          type: 'map',
          mapType: this.province,
          mapLocation: {
              x: 'left',
              y: 'top',
              width: '30%'
          },
          roam: true,
          selectedMode : 'single',
          itemStyle:{
              //normal:{label:{show:true}},
              emphasis:{label:{show:true}}
          },
          data:[
              {name: '重庆市',selected:false},
              {name: '北京市',selected:false},
              {name: '天津市',selected:false},
              {name: '上海市',selected:false},
              {name: '香港',selected:false},
              {name: '澳门',selected:false},
              {name: '巴音郭楞蒙古自治州',selected:false},
              {name: '和田地区',selected:false},
              {name: '哈密地区',selected:false},
              {name: '阿克苏地区',selected:false},
              {name: '阿勒泰地区',selected:false},
              {name: '喀什地区',selected:false},
              {name: '塔城地区',selected:false},
              {name: '昌吉回族自治州',selected:false},
              {name: '克孜勒苏柯尔克孜自治州',selected:false},
              {name: '吐鲁番地区',selected:false},
              {name: '伊犁哈萨克自治州',selected:false},
              {name: '博尔塔拉蒙古自治州',selected:false},
              {name: '乌鲁木齐市',selected:false},
              {name: '克拉玛依市',selected:false},
              {name: '阿拉尔市',selected:false},
              {name: '图木舒克市',selected:false},
              {name: '五家渠市',selected:false},
              {name: '石河子市',selected:false},
              {name: '那曲地区',selected:false},
              {name: '阿里地区',selected:false},
              {name: '日喀则地区',selected:false},
              {name: '林芝地区',selected:false},
              {name: '昌都地区',selected:false},
              {name: '山南地区',selected:false},
              {name: '拉萨市',selected:false},
              {name: '呼伦贝尔市',selected:false},
              {name: '阿拉善盟',selected:false},
              {name: '锡林郭勒盟',selected:false},
              {name: '鄂尔多斯市',selected:false},
              {name: '赤峰市',selected:false},
              {name: '巴彦淖尔市',selected:false},
              {name: '通辽市',selected:false},
              {name: '乌兰察布市',selected:false},
              {name: '兴安盟',selected:false},
              {name: '包头市',selected:false},
              {name: '呼和浩特市',selected:false},
              {name: '乌海市',selected:false},
              {name: '海西蒙古族藏族自治州',selected:false},
              {name: '玉树藏族自治州',selected:false},
              {name: '果洛藏族自治州',selected:false},
              {name: '海南藏族自治州',selected:false},
              {name: '海北藏族自治州',selected:false},
              {name: '黄南藏族自治州',selected:false},
              {name: '海东地区',selected:false},
              {name: '西宁市',selected:false},
              {name: '甘孜藏族自治州',selected:false},
              {name: '阿坝藏族羌族自治州',selected:false},
              {name: '凉山彝族自治州',selected:false},
              {name: '绵阳市',selected:false},
              {name: '达州市',selected:false},
              {name: '广元市',selected:false},
              {name: '雅安市',selected:false},
              {name: '宜宾市',selected:false},
              {name: '乐山市',selected:false},
              {name: '南充市',selected:false},
              {name: '巴中市',selected:false},
              {name: '泸州市',selected:false},
              {name: '成都市',selected:false},
              {name: '资阳市',selected:false},
              {name: '攀枝花市',selected:false},
              {name: '眉山市',selected:false},
              {name: '广安市',selected:false},
              {name: '德阳市',selected:false},
              {name: '内江市',selected:false},
              {name: '遂宁市',selected:false},
              {name: '自贡市',selected:false},
              {name: '黑河市',selected:false},
              {name: '大兴安岭地区',selected:false},
              {name: '哈尔滨市',selected:false},
              {name: '齐齐哈尔市',selected:false},
              {name: '牡丹江市',selected:false},
              {name: '绥化市',selected:false},
              {name: '伊春市',selected:false},
              {name: '佳木斯市',selected:false},
              {name: '鸡西市',selected:false},
              {name: '双鸭山市',selected:false},
              {name: '大庆市',selected:false},
              {name: '鹤岗市',selected:false},
              {name: '七台河市',selected:false},
              {name: '酒泉市',selected:false},
              {name: '张掖市',selected:false},
              {name: '甘南藏族自治州',selected:false},
              {name: '武威市',selected:false},
              {name: '陇南市',selected:false},
              {name: '庆阳市',selected:false},
              {name: '白银市',selected:false},
              {name: '定西市',selected:false},
              {name: '天水市',selected:false},
              {name: '兰州市',selected:false},
              {name: '平凉市',selected:false},
              {name: '临夏回族自治州',selected:false},
              {name: '金昌市',selected:false},
              {name: '嘉峪关市',selected:false},
              {name: '普洱市',selected:false},
              {name: '红河哈尼族彝族自治州',selected:false},
              {name: '文山壮族苗族自治州',selected:false},
              {name: '曲靖市',selected:false},
              {name: '楚雄彝族自治州',selected:false},
              {name: '大理白族自治州',selected:false},
              {name: '临沧市',selected:false},
              {name: '迪庆藏族自治州',selected:false},
              {name: '昭通市',selected:false},
              {name: '昆明市',selected:false},
              {name: '丽江市',selected:false},
              {name: '西双版纳傣族自治州',selected:false},
              {name: '保山市',selected:false},
              {name: '玉溪市',selected:false},
              {name: '怒江傈僳族自治州',selected:false},
              {name: '德宏傣族景颇族自治州',selected:false},
              {name: '百色市',selected:false},
              {name: '河池市',selected:false},
              {name: '桂林市',selected:false},
              {name: '南宁市',selected:false},
              {name: '柳州市',selected:false},
              {name: '崇左市',selected:false},
              {name: '来宾市',selected:false},
              {name: '玉林市',selected:false},
              {name: '梧州市',selected:false},
              {name: '贺州市',selected:false},
              {name: '钦州市',selected:false},
              {name: '贵港市',selected:false},
              {name: '防城港市',selected:false},
              {name: '北海市',selected:false},
              {name: '怀化市',selected:false},
              {name: '永州市',selected:false},
              {name: '邵阳市',selected:false},
              {name: '郴州市',selected:false},
              {name: '常德市',selected:false},
              {name: '湘西土家族苗族自治州',selected:false},
              {name: '衡阳市',selected:false},
              {name: '岳阳市',selected:false},
              {name: '益阳市',selected:false},
              {name: '长沙市',selected:false},
              {name: '株洲市',selected:false},
              {name: '张家界市',selected:false},
              {name: '娄底市',selected:false},
              {name: '湘潭市',selected:false},
              {name: '榆林市',selected:false},
              {name: '延安市',selected:false},
              {name: '汉中市',selected:false},
              {name: '安康市',selected:false},
              {name: '商洛市',selected:false},
              {name: '宝鸡市',selected:false},
              {name: '渭南市',selected:false},
              {name: '咸阳市',selected:false},
              {name: '西安市',selected:false},
              {name: '铜川市',selected:false},
              {name: '清远市',selected:false},
              {name: '韶关市',selected:false},
              {name: '湛江市',selected:false},
              {name: '梅州市',selected:false},
              {name: '河源市',selected:false},
              {name: '肇庆市',selected:false},
              {name: '惠州市',selected:false},
              {name: '茂名市',selected:false},
              {name: '江门市',selected:false},
              {name: '阳江市',selected:false},
              {name: '云浮市',selected:false},
              {name: '广州市',selected:false},
              {name: '汕尾市',selected:false},
              {name: '揭阳市',selected:false},
              {name: '珠海市',selected:false},
              {name: '佛山市',selected:false},
              {name: '潮州市',selected:false},
              {name: '汕头市',selected:false},
              {name: '深圳市',selected:false},
              {name: '东莞市',selected:false},
              {name: '中山市',selected:false},
              {name: '延边朝鲜族自治州',selected:false},
              {name: '吉林市',selected:false},
              {name: '白城市',selected:false},
              {name: '松原市',selected:false},
              {name: '长春市',selected:false},
              {name: '白山市',selected:false},
              {name: '通化市',selected:false},
              {name: '四平市',selected:false},
              {name: '辽源市',selected:false},
              {name: '承德市',selected:false},
              {name: '张家口市',selected:false},
              {name: '保定市',selected:false},
              {name: '唐山市',selected:false},
              {name: '沧州市',selected:false},
              {name: '石家庄市',selected:false},
              {name: '邢台市',selected:false},
              {name: '邯郸市',selected:false},
              {name: '秦皇岛市',selected:false},
              {name: '衡水市',selected:false},
              {name: '廊坊市',selected:false},
              {name: '恩施土家族苗族自治州',selected:false},
              {name: '十堰市',selected:false},
              {name: '宜昌市',selected:false},
              {name: '襄樊市',selected:false},
              {name: '黄冈市',selected:false},
              {name: '荆州市',selected:false},
              {name: '荆门市',selected:false},
              {name: '咸宁市',selected:false},
              {name: '随州市',selected:false},
              {name: '孝感市',selected:false},
              {name: '武汉市',selected:false},
              {name: '黄石市',selected:false},
              {name: '神农架林区',selected:false},
              {name: '天门市',selected:false},
              {name: '仙桃市',selected:false},
              {name: '潜江市',selected:false},
              {name: '鄂州市',selected:false},
              {name: '遵义市',selected:false},
              {name: '黔东南苗族侗族自治州',selected:false},
              {name: '毕节地区',selected:false},
              {name: '黔南布依族苗族自治州',selected:false},
              {name: '铜仁地区',selected:false},
              {name: '黔西南布依族苗族自治州',selected:false},
              {name: '六盘水市',selected:false},
              {name: '安顺市',selected:false},
              {name: '贵阳市',selected:false},
              {name: '烟台市',selected:false},
              {name: '临沂市',selected:false},
              {name: '潍坊市',selected:false},
              {name: '青岛市',selected:false},
              {name: '菏泽市',selected:false},
              {name: '济宁市',selected:false},
              {name: '德州市',selected:false},
              {name: '滨州市',selected:false},
              {name: '聊城市',selected:false},
              {name: '东营市',selected:false},
              {name: '济南市',selected:false},
              {name: '泰安市',selected:false},
              {name: '威海市',selected:false},
              {name: '日照市',selected:false},
              {name: '淄博市',selected:false},
              {name: '枣庄市',selected:false},
              {name: '莱芜市',selected:false},
              {name: '赣州市',selected:false},
              {name: '吉安市',selected:false},
              {name: '上饶市',selected:false},
              {name: '九江市',selected:false},
              {name: '抚州市',selected:false},
              {name: '宜春市',selected:false},
              {name: '南昌市',selected:false},
              {name: '景德镇市',selected:false},
              {name: '萍乡市',selected:false},
              {name: '鹰潭市',selected:false},
              {name: '新余市',selected:false},
              {name: '南阳市',selected:false},
              {name: '信阳市',selected:false},
              {name: '洛阳市',selected:false},
              {name: '驻马店市',selected:false},
              {name: '周口市',selected:false},
              {name: '商丘市',selected:false},
              {name: '三门峡市',selected:false},
              {name: '新乡市',selected:false},
              {name: '平顶山市',selected:false},
              {name: '郑州市',selected:false},
              {name: '安阳市',selected:false},
              {name: '开封市',selected:false},
              {name: '焦作市',selected:false},
              {name: '许昌市',selected:false},
              {name: '濮阳市',selected:false},
              {name: '漯河市',selected:false},
              {name: '鹤壁市',selected:false},
              {name: '大连市',selected:false},
              {name: '朝阳市',selected:false},
              {name: '丹东市',selected:false},
              {name: '铁岭市',selected:false},
              {name: '沈阳市',selected:false},
              {name: '抚顺市',selected:false},
              {name: '葫芦岛市',selected:false},
              {name: '阜新市',selected:false},
              {name: '锦州市',selected:false},
              {name: '鞍山市',selected:false},
              {name: '本溪市',selected:false},
              {name: '营口市',selected:false},
              {name: '辽阳市',selected:false},
              {name: '盘锦市',selected:false},
              {name: '忻州市',selected:false},
              {name: '吕梁市',selected:false},
              {name: '临汾市',selected:false},
              {name: '晋中市',selected:false},
              {name: '运城市',selected:false},
              {name: '大同市',selected:false},
              {name: '长治市',selected:false},
              {name: '朔州市',selected:false},
              {name: '晋城市',selected:false},
              {name: '太原市',selected:false},
              {name: '阳泉市',selected:false},
              {name: '六安市',selected:false},
              {name: '安庆市',selected:false},
              {name: '滁州市',selected:false},
              {name: '宣城市',selected:false},
              {name: '阜阳市',selected:false},
              {name: '宿州市',selected:false},
              {name: '黄山市',selected:false},
              {name: '巢湖市',selected:false},
              {name: '亳州市',selected:false},
              {name: '池州市',selected:false},
              {name: '合肥市',selected:false},
              {name: '蚌埠市',selected:false},
              {name: '芜湖市',selected:false},
              {name: '淮北市',selected:false},
              {name: '淮南市',selected:false},
              {name: '马鞍山市',selected:false},
              {name: '铜陵市',selected:false},
              {name: '南平市',selected:false},
              {name: '三明市',selected:false},
              {name: '龙岩市',selected:false},
              {name: '宁德市',selected:false},
              {name: '福州市',selected:false},
              {name: '漳州市',selected:false},
              {name: '泉州市',selected:false},
              {name: '莆田市',selected:false},
              {name: '厦门市',selected:false},
              {name: '丽水市',selected:false},
              {name: '杭州市',selected:false},
              {name: '温州市',selected:false},
              {name: '宁波市',selected:false},
              {name: '舟山市',selected:false},
              {name: '台州市',selected:false},
              {name: '金华市',selected:false},
              {name: '衢州市',selected:false},
              {name: '绍兴市',selected:false},
              {name: '嘉兴市',selected:false},
              {name: '湖州市',selected:false},
              {name: '盐城市',selected:false},
              {name: '徐州市',selected:false},
              {name: '南通市',selected:false},
              {name: '淮安市',selected:false},
              {name: '苏州市',selected:false},
              {name: '宿迁市',selected:false},
              {name: '连云港市',selected:false},
              {name: '扬州市',selected:false},
              {name: '南京市',selected:false},
              {name: '泰州市',selected:false},
              {name: '无锡市',selected:false},
              {name: '常州市',selected:false},
              {name: '镇江市',selected:false},
              {name: '吴忠市',selected:false},
              {name: '中卫市',selected:false},
              {name: '固原市',selected:false},
              {name: '银川市',selected:false},
              {name: '石嘴山市',selected:false},
              {name: '儋州市',selected:false},
              {name: '文昌市',selected:false},
              {name: '乐东黎族自治县',selected:false},
              {name: '三亚市',selected:false},
              {name: '琼中黎族苗族自治县',selected:false},
              {name: '东方市',selected:false},
              {name: '海口市',selected:false},
              {name: '万宁市',selected:false},
              {name: '澄迈县',selected:false},
              {name: '白沙黎族自治县',selected:false},
              {name: '琼海市',selected:false},
              {name: '昌江黎族自治县',selected:false},
              {name: '临高县',selected:false},
              {name: '陵水黎族自治县',selected:false},
              {name: '屯昌县',selected:false},
              {name: '定安县',selected:false},
              {name: '保亭黎族苗族自治县',selected:false},
              {name: '五指山市',selected:false}
          ]
        }
      ]
    }
  }

}
</script>

<style lang="sass">
.province {
  width: 100%;
  height: 100%;
}
</style>
